# Generated by Django 4.1.9 on 2023-06-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='r_lookupdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimaryFunction', models.CharField(max_length=112)),
                ('SecondaryFunction', models.CharField(max_length=50)),
                ('PrimaryFunction_ImageName', models.CharField(max_length=50)),
                ('SecondaryFunction_ImageName', models.CharField(max_length=50)),
                ('canDemandSecondaryFunction', models.CharField(max_length=50)),
                ('isAvailableSecondaryFunction', models.CharField(max_length=50)),
                ('areFunctionInUse', models.CharField(max_length=50)),
                ('PrimaryFunction_hindi', models.CharField(max_length=50)),
                ('SecondaryFunction_hindi', models.CharField(max_length=50)),
            ],
        ),
    ]
