# Generated by Django 4.1.9 on 2023-06-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k2k', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='d_user_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('village', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('PrimaryFunction', models.CharField(max_length=50)),
                ('SecondaryFunction', models.CharField(max_length=50)),
                ('tehsil', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='r_district_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('village', models.CharField(max_length=50)),
                ('village_hindi', models.CharField(max_length=50)),
                ('gram_panchayat', models.CharField(max_length=50)),
                ('tehsil', models.CharField(max_length=50)),
                ('tehsil_hindi', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district_hindi', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('state_hindi', models.CharField(max_length=50)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='r_farmingassets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('seqNo', models.IntegerField()),
                ('assetType', models.CharField(max_length=50)),
                ('assetsubType', models.CharField(max_length=50)),
                ('assetNameEnglish', models.CharField(max_length=50)),
                ('assetNamehindi', models.CharField(max_length=50)),
                ('assetCapacityUnit', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('inUse', models.CharField(max_length=50)),
                ('activeInK2App', models.CharField(max_length=50)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='r_k2support',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vedioLink', models.URLField(max_length=225)),
                ('vedioType', models.CharField(max_length=112)),
                ('vediok2Page', models.CharField(max_length=112)),
                ('vedioLinkHindi', models.URLField(max_length=225)),
                ('vedioLinkLocal', models.URLField(max_length=225)),
                ('state', models.CharField(max_length=112)),
                ('district', models.CharField(max_length=112)),
                ('activeInK2App', models.CharField(max_length=112)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='r_state_district',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('state_hindi', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district_hindi', models.CharField(max_length=50)),
                ('activeInK2App', models.CharField(max_length=50)),
                ('population2021', models.CharField(max_length=50)),
                ('areaInKmSquare', models.CharField(max_length=50)),
                ('densityPerKm', models.CharField(max_length=50)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
